config/routes.rb
Proj::Application.routes.draw do
resources :blackflag
resources :existinguser

  root 'blackflag#index'

end

app/models/blackflag.rb
class Blackflag < ActiveRecord::Base
#validates_presence_of :EmpID 
#attr_accessible :EmpID,:reload_on
def self.to_csv(options={})
CSV.generate options do |csv|
csv<<column_names
all.each do |blackflag|
csv<<blackflag.attributes.values_at(*column_names)
end
end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blackflag_controller.rb
class BlackflagController < ApplicationController
layout 'standard'
def index
  # @blackflag = Blackflag.all
  @blackflag=Blackflag.all
  
 
  end

def new
 @blackflag = Blackflag.new
end

def edit
  @blackflag = Blackflag.find(params[:id])
end

def update
  @blackflag = Blackflag.find(params[:id])

  if @blackflag.update(post_params)
    redirect_to action: :show, id: @blackflag.id
  else
      render 'edit'
  end
end

	
def create
@blackflag = Blackflag.new(params[:blackflag].permit(:EmpID, :Name,:ATTUID,:MailID,:GitHubID,:APIGEE_ID,:Foundry_ID,:ContactNum,:DOB))
  if @blackflag.save
  #  redirect_to @blackflag
	render 'msg'
	
  else
    render 'new'
  end
end
  
def show
  @blackflag = Blackflag.all
   respond_to do |format|
  format.html
  format.csv{send_data:@blackflag.to_csv}
  #format.xls{send_data:@blackflag.to_csv}
  end
end
end

app/controllers/existinguser_controller.rb
class ExistinguserController < ApplicationController
def index
  @blackflag = Blackflag.find(params[:EmpID])
end

def edit
@blackflag=Blackflag.find(params[:EmpID])
end
def new
 
end

	
def create
 #@blackflag = Blackflag.find_by_sql("SELECT * FROM blackflags WHERE blackflags.EmpID=83555")
 @blackflag = Blackflag.find(params[:ID])
   if @blackflag.find
   render 'show'
   else
   render 'msg'
   end
end
  
  
def show
   @blackflag = Blackflag.all
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blackflag_helper.rb
module BlackflagHelper
end

app/helpers/existinguser_helper.rb
module ExistinguserHelper
end

app/views/blackflag/index.html.erb
<h1>Hi Welcome to Blackflag app</h1>
<h1>Hello, user!</h1>

<%=image_tag "Jellyfish.jpg"%>
<%= link_to "ClickMe if you are new user!", new_blackflag_path %>	

app/views/blackflag/msg.html.erb
<h3>Your details has been saved successfully</h3>
<%=link_to "Home Page",blackflag_index_path%></br>

app/views/blackflag/new.html.erb
<h1>Register here with your details if you are new user</h1>
<%= form_for :blackflag, url: blackflag_index_path do |f| %>

 <b> <p>    <%= f.label :EmpID%>   <%= f.text_field:EmpID %>  </p>
  <p>    <%= f.label :Name %>    <%= f.text_field :Name %>  </p>
  <p>    <%= f.label :ATTUID %>    <%= f.text_field :ATTUID %>  </p>
  <p>    <%= f.label :MailID %>    <%= f.text_field :MailID %>  </p>
  <p>    <%= f.label :GitHubID %>    <%= f.text_field :GitHubID %>  </p>
  <p>    <%= f.label :APIGEE_ID %>    <%= f.text_field :APIGEE_ID %>  </p>
  <p>    <%= f.label :Foundry_ID %>    <%= f.text_field :Foundry_ID %>  </p>
  <p>    <%= f.label :ContactNum %>    <%= f.text_field :ContactNum %>  </p>
  <p>    <%= f.label :DOB %>    <%= f.text_field :DOB %>  </p>
  <p>    <%= f.submit %>  </p></b>
<% end %>
<h1>Follow the Link to see existing user details</h1>
 <%=link_to "Click here To View Existing User Details", 'show'%>

app/views/blackflag/show.html.erb
<h1>Listing teams</h1>

<table border="2">
  <tr>
    <th>Name</th>
    <th>EmpId</th>
    <th>Contactno</th>
	<th>EmailID</th>
	<th>DOB</th>
	<th>ATTUID </th>
	<th>GitHubID </th>
	<th>APIGEE_ID </th>
	<th>Foundry_ID </th>
  </tr>

<% @blackflag.each do |team| %>
  <tr>
    <td><%=h team.EmpID %></td>
    <td><%=h team.Name %></td>
    <td><%=h team.ContactNum %></td>
	<td><%=h team.MailID%></td>
	<td><%=h team.DOB%></td>
	<td><%=h team.ATTUID%></td>
	<td><%=h team.GitHubID %></td>
	<td><%=h team.APIGEE_ID %></td>
	<td><%=h team.Foundry_ID %></td>
  </tr>
<% end %>
</table>

app/views/blackflag/viewall.html.erb
<h1>Listing teams</h1>

<table>
  <tr>
    <th>Name</th>
    <th>EmpId</th>
    <th>Contactno</th>
	<th>EmailID</th>
	<th>DOB</th>
	<th>ATTUID </th>
	<th>GitHubID </th>
	<th>APIGEE_ID </th>
	<th>Foundry_ID </th>
  </tr>

<% @blackflag.each do |team| %>
  <tr>
    <td><%=h team.EmpID %></td>
    <td><%=h team.Name %></td>
    <td><%=h team.ContactNum %></td>
	<td><%=h team.MailID%></td>
	<td><%h team.DOB%></td>
	<td><%=h team.ATTUID%></td>
	<td><%=h team.GitHubID %></td>
	<td><%=h team.APIGEE_ID %></td>
	<td><%=h team.Foundry_ID %></td>
  </tr>
<% end %>
</table>

app/views/existinguser/edit.html.erb
<h1>Listing teams</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Id</th>
    <th>Contactno</th>
	<th>EmailID</th>
	<th>ATTID</th>
	<th>DOB</th>
  </tr>

<% @blackflag.each do |team| %>
  <tr>
    <td><%=h team.Name %></td>
    <td><%=h team.EmpID %></td>
    <td><%=h team.ContactNum %></td>
	<td><%=h team.MailID%></td>
	<td><%=h team.ATTUID%></td>
	<td><%h team.DOB%></td>
  </tr>
<% end %>
</table>

app/views/existinguser/index.html.erb
<%= form_for :blackflag,url:existinguser_index_path do |f| %>
<p>Existing users enter your employee ID</p>
  <p>    <%= f.label :EmpID %>    <%= f.text_field :EmpID %>  </p>
   <p>    <%= f.submit :Enter %>  </p>
<% end %>
<%=link_to "View_All_Details", 'show'%>

app/views/existinguser/new.html.erb
<%= form_for :blackflag,url:existinguser_index_path do |f| %>
<p>Existing users enter your employee ID</p>
  <p>    <%= f.label :EmpID %>    <%= f.text_field :EmpID %>  </p>
   <p>    <%= f.submit :Enter %>  </p>
<% end %>
<%=link_to "View_All_Details", 'show'%>

app/views/existinguser/show.html.erb
<h1>Listing teams</h1>

<table>
  <tr>
    <th>Name</th>
    <th>EmpId</th>
    <th>Contactno</th>
	<th>EmailID</th>
	<th>DOB</th>
	<th>ATTUID </th>
	<th>GitHubID </th>
	<th>APIGEE_ID </th>
	<th>Foundry_ID </th>
  </tr>

<% @blackflag.each do |team| %>
  <tr>
    <td><%=h team.EmpID %></td>
    <td><%=h team.Name %></td>
    <td><%=h team.ContactNum %></td>
	<td><%=h team.MailID%></td>
	<td><%h team.DOB%></td>
	<td><%=h team.ATTUID%></td>
	<td><%=h team.GitHubID %></td>
	<td><%=h team.APIGEE_ID %></td>
	<td><%=h team.Foundry_ID %></td>
  </tr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proj</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtmll/DTD/xhtmll-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;.charset=iso-8859-1"/>
<meta http-equiv="Content-Language" content="en-us"/>
<title>Blackflag Application</title>
<%=stylesheet_link_tag "style"%>
</head>
<body id="library">
<div id="container">
<div id="header">
<h1>Blackflag Application</h1>
<h3>Blackflag Application powered by Ruby on rails</h3>
</div>
<div id="content">
<%=yield-%>
</div>
<div id="sidebar"></div>
</div>
</body>
</html>